Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    [Route("/About")]
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/CarsController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Web.Mediator.Arguments;
using Web.Mediator.Requests;
using Web.ViewModels;

namespace Web.Controllers;

[Route("[controller]")]
public class CarsController : Controller
{
    private readonly IMediator _mediator;
    private const int MaxPageSize = 12;

    public CarsController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet()]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("catalog")]
    public async Task<IActionResult> GetPage(int page, int count, bool? enablePagination)
    {
        var pageProducts = await _mediator.Send(new GetCarsPageRequest(new(page, count)));
        var totalProducts = await _mediator.Send(new GetCarsRequest(new()));
        return PartialView("Partials/_CarsCatalog", new IndexViewModel(pageProducts, new PageViewModel(page, count, totalProducts.Length, enablePagination)));
    }

    [HttpGet("{mark}/{model}")]
    public async Task<IActionResult> CarDetails(string mark, string model)
    {
        var carProduct = await _mediator.Send(new GetCarRequest(new(mark, model)));
        return View(carProduct);
    }

    [HttpPost("sell")]
    public async Task<IActionResult> Sell([FromForm] SellRequestArguments arguments)
    {
        await _mediator.Send(new SellRequest(arguments));
        return RedirectToAction("Index");
    }
}

Web/Controllers/ShopsController.cs
using Microsoft.AspNetCore.Mvc;
using Shared;

namespace Web.Controllers
{
    [Route("[controller]")]
    public class ShopsController : Controller
    {
        [HttpGet()]
        public IActionResult Index([FromServices] IEnumerable<StorageConfiguration> config)
        {
            return View(config);
        }
    }
}

Web/Views/Shared/_Head.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - AutoShop</title>
<link rel="icon" type="image/x-icon" href="~/img/icons/favicon.ico">
<link rel="stylesheet" href="~/twitter-bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/font-awesome/css/all.css" />
<link rel="stylesheet" href="~/font-awesome/css/v4-shims.min.css" />
<link rel="stylesheet" href="~/bootstrap-icons/font/bootstrap-icons.css" />
<link rel="stylesheet" href="~/css/site.css" />

Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("_Head")
    <link rel="stylesheet" href="~/css/login.css" />
</head>
<body>
    <div class="bg"></div>
    <div class="bg bg2"></div>
    <div class="bg bg3"></div>
    <div>
        <section class="vh-100 gradient-custom">
            <div class="container py-2 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div class="card bg-dark text-white" style="border-radius: 0;">
                            <div class="card-body px-5 text-center">
                                <a class="display-5 logo-link text-white d-block form-logo" asp-controller="Home" asp-action="Index" style="text-decoration: none;">
                                    <span>Auto</span><span class="red-logo">shop</span>
                                </a>
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/login.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_UserLayout.cshtml
@using System.Security.Claims
@using Model.Application
@using Web.Models
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("_Head")
    @RenderSection("Styles", false)
    <link rel="stylesheet" href="~/css/user-layout.css" />
</head>
@functions
{
    public string GetUsername(string email)
    {
        return email.Substring(0, email.IndexOf('@'));
    }
}
<body class="d-flex flex-column">
    <div id="page-content">

        @*User navigation panel start*@
        <header class="layout-dark-color @ViewData["NavType"] role="banner">
            <nav class="navbar navbar-expand-md">
                <div class="container">
                    <div class="col-md-3 col row text-center text-lg-start">
                        <a class="navbar-logo m-0 logo-link" style="font-size: 1.6rem;" asp-controller="Home"><span>Auto</span><span class="red-logo">shop</span></a>
                        <button class="navbar-toggler collapsed float-end my-2 text-white p-2" id="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse" aria-controls="#navbar-collapse" aria-expanded="false">
                            <i id="toggler-icon" class="fa fa-navicon"></i>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbar-collapse">

                        @*Links part start*@
                        <div class="col-12 col-md-8 d-flex">
                            <ul class="navbar-nav m-auto pl-lg-5 pl-0 menu center justify-content-around" style="flex-grow: 1;">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Cars" asp-action="Index">Cars</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Shops" asp-action="Index">Shops</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="About" asp-action="Index">About</a>
                                </li>

                                @if (User.IsInRole(nameof(RoleName.Admin)))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="Admin" asp-action="Index">Admin</a>
                                    </li>
                                }
                                @if (User.IsInRole(nameof(RoleName.User)))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white menu-link" asp-controller="Cart" asp-action="Index">
                                            <span class="cart-text">Cart</span><i class="ms-2 fa fa-shopping-cart"></i>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                        @*Links part end*@

                        @*User block start*@
                        <div class="col-12 col-md-4 text-center text-md-end pb-1">
                            <ul class="navbar-nav justify-content-end user-btn-container" style="flex-grow: 1;">
                                
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item login-button">
                                        <a class="nav-link " asp-controller="Account" asp-action="Login">Sign in <i class="mx-2 fa fa-sign-in-alt"></i></a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item d-block">
                                        <a id="user-btn" class="nav-link float-end">
                                            <p class="username-text wide-text-overflow">
                                            @GetUsername(User.FindFirst(ClaimTypes.Email)?.Value)
                                            </p>
                                        </a>
                                    </li>
                                     <li class="nav-item d-block">
                                        @using (Html.BeginForm("Logout", "Account", FormMethod.Post))
                                         {
                                            <button id="logout-btn" class="nav-link px-2" type="submit">
                                                    <span class="d-md-none">Logout</span><i class="ms-2 fa fa-sign-in-alt"></i>
                                            </button>
                                         }
                                    </li>
                                }

                            </ul>
                        </div>
                        @*User block end*@

                    </div>
                </div>
            </nav>
        </header>
        @*User navigation panel end*@

        @*Content block start*@
        <main class="p-0">
            @RenderBody()
        </main>
        @*Content block end*@

    </div>

    @*Footer start*@
    <footer class="pt-3 px-5 text-white layout-dark-color">
        <div class="container">
            <div class="row">

                @*Logo column start*@
                <div class="col-12 col-md-5 order-3 order-md-0 text-center text-md-start py-4 pt-md-0">
                    <div class="logo-part p-0">
                        <span class="logo-link lg-font"><span>Auto</span><span class="red-logo">shop</span></span>
                    </div>
                    <div class="white-50">
                        &copy; All rights reserved
                    </div>
                </div>
                @*Logo column end*@

                @*Socials column start*@
                <div class="col-12 col-md-4 pt-4 pt-md-0 text-center text-md-start ">
                    <span class="footer-header">Follow us</span>
                    <ul class="list-unstyled mb-1 pt-2 d-flex list-inline justify-content-center justify-content-md-start socials">
                        <li><a href="https://bitbucket.org/tumashst/arcde/"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="https://bitbucket.org/tumashst/arcde/"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://bitbucket.org/tumashst/arcde/"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
                @*Socials column end*@

                @*Contacts column start*@
                <div class="col-12 col-md-3 py-4 pt-md-0 text-center text-md-start">
                    <span class="footer-header">Contact us</span>
                    <ul class="list-unstyled mb-1 pt-2 list-inline contacts">
                        <li><a><i class="fa fa-envelope me-2"></i>lpglobalteam@mail.ru</a></li>
                        <li><a><i class="fa fa-phone me-2"></i>+1 23 02 19 2022 </a></li>
                    </ul>
                </div>
                @*Contacts column end*@

            </div>
        </div>
    </footer>
    @*Footer end*@

    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>